version: "3"
services:
  # mongodb:
  #   image: mongo:latest
  #   volumes:
  #     - mongo-data:/data/db
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - backend
  myredis:
    image: redis
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
  pushbomb:
    image: 172.17.8.101:5000/nodeserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - virtualhost
    ports:
      - 7777:7777
    deploy:
      mode: replicated
      replicas: 6
    
  virtualhost:
    image: cendra/virtualhost
    networks: 
      - virtualhost
    mode: global
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    mount: type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock
    ports: 
      - 80:80
    environment:
      - REDIS=myredis
networks:
  virtualhost:
    driver: overlay