version: "3"
services:
  # mongodb:
  #   image: mongo:latest
  #   volumes:
  #     - mongo-data:/data/db
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - backend
  pushbomb:
    image: core-01:5000/nodeserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    ports:
      - 7777:7777
networks:
  backend:
    driver: overlay
volumes:
  mongo-data: