version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
  pushbomb:
    image: nodeserver
    networks:
      - backend
    ports:
      - 7777:7777
networks:
  backend:
    driver: overlay
volumes:
  mongo-data: