version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 27017:27017
    networks:
      - backend
  pushbomb:
    image: localhost:5000/nodeserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    ports:
      - 7777:7777
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # command: --templates http://templates/templates.json -d /data -H tcp://<DOCKER_HOST>:<DOCKER_PORT>
    networks:
      - backend
    ports:
      - 9000:9000
  registry:
    image: registry
    networks:
      - backend
    ports:
      - 5000:5000
networks:
  backend:
    driver: overlay
volumes:
  mongo-data: