---
# remote:
#     hosts:
#         aws:
#             ansible_host: 52.78.147.136 
#             ansible_user: ubuntu 
#             ansible_ssh_private_key_file:  ~/.ssh/monodev.pem

vagrant:
    vars:
        ansible_host: 127.0.0.1
        ansible_connection: ssh
        ansible_user: ubuntu
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes'
    hosts:
        master:
            ansible_port: 2222
            ansible_ssh_private_key_file: /Users/kimdongho/workspaces/node/pushbomb/.vagrant/machines/master/virtualbox/private_key
        # registry:
        #     ansible_port: 2222 
        #     ansible_ssh_private_key_file: /Users/kimdongho/workspaces/node/pushbomb/.vagrant/machines/registry/virtualbox/private_key
workers:
    vars:
        ansible_host: 127.0.0.1
        ansible_connection: ssh  
        ansible_user: ubuntu 
        ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes'
    hosts:
        worker:
            ansible_port: 2206
            ansible_ssh_private_key_file: /Users/kimdongho/workspaces/node/pushbomb/.vagrant/machines/worker/virtualbox/private_key