---
# remote:
#     hosts:
#         aws:
#             ansible_host: 52.78.147.136 
#             ansible_user: ubuntu 
#             ansible_ssh_private_key_file:  ~/.ssh/monodev.pem


vagrant:
    hosts:
        core-01:
            ansible_host: 127.0.0.1
            ansible_connection: ssh  
            ansible_port: 2222 
            ansible_user: ubuntu 
            ansible_ssh_private_key_file: /Users/kimdongho/workspaces/node/pushbomb/.vagrant/machines/core-01/virtualbox/private_key
            ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes'
workers:
    hosts:
        core-02:
            ansible_host: 127.0.0.1
            ansible_connection: ssh  
            ansible_port: 2205 
            ansible_user: ubuntu 
            ansible_ssh_private_key_file: /Users/kimdongho/workspaces/node/pushbomb/.vagrant/machines/core-02/virtualbox/private_key
            ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes'
        # core-03:
        #     ansible_host: 172.17.8.103
        #     ansible_connection: ssh  
        #     ansible_port: 2208 
        #     ansible_user: ubuntu 
        #     ansible_ssh_private_key_file: /Users/kimdongho/workspaces/node/pushbomb/.vagrant/machines/core-03/virtualbox/private_key
        #     ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes'